### ISSUE TITLE
Podman fallback for container build in molecule test

### ISSUE THREAD

**Issue by thywyn** [vexxhost/atmosphere#106]
Would like to have a fallback to podman for the operator build in the molecule test for those environments that do not use docker

**Comment by mnaser** [comment]
@thywyn can you check if that branch works for you locally?

you don't have to run the whole molecule stack, you can just clone it and run `molecule dependency` and see how that goes.

Thanks

**Comment by mnaser** [comment]
hrm, okay so I think a big part of this is the fact that we're using Buildkit to build those images (aka `docker buildx`) and I think Podman does not support these frontends at all, which means that we can't do a lot of the fancy stuff to allow building things more effectively.

I think we'll have to think about this a bit more, as its' not as straight forward.

**Comment by thywyn** [comment]
one other thing is that the mount type "cache" is supported with podman 4.x+. You can get an installable package here: `wget http://ftp.us.debian.org/debian/pool/main/libp/libpod/podman_4.2.0+ds1-3_amd64.deb for 22.04`.  For 20.04, podman would have to be built from source.

**Comment by mnaser** [comment]
I think the only way to successfully move forward with this would be to create a `Containerfile` and write some tests to keep them relatively in sync.

Podman is neat but it seems to be missing a fair bit of features such as Buildkit.  I don't know if we can do a whole lot about supporting the podman images out of the box.

If you have a functional `Containerfile` that can be used with Podman, could you perhaps send that as a PR?   Since I think it will be hard to support two different and distinct build tools for the images and we're mostly all using Docker here.

**Comment by thywyn** [comment]
Closing this issue since it is a nice to have and cannot spend time on this as needed.  Thanks for the input back.. I have it in my own backlog to follow-up on this
