### ISSUE TITLE
multipathd ppa only for Jammy

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#1574]
The current [PPA](https://github.com/vexxhost/atmosphere/blob/main/roles/multipathd/defaults/main.yml#L23) is only for Jammy.

Our current Computes are on Focal. Would be create if you also add the Jammy packages.

**Comment by mnaser** [comment]
@mpiscaer The reason why there are Jammy packages is because Portworx (for using Pure Storage as a CSI) gives this error:

```
WARNING: multipath version 0.8.7 (between 0.7.7 and 0.9.3) is known to have issues with crashing and/or high CPU usage. If possible, please upgrade multipathd to version 0.9.4 or higher to avoid this issue.
```

This is why we have 0.9.5 back ported.  If you have a Focal compute node, then you don't really have this issue because Portworx CSI doesn't even run on the compute nodes (and we don't really need to update it).

**Comment by mnaser** [comment]
I see there is an error adding the PPA on Focal.
