### ISSUE TITLE
Atmosphere Operator: optional deployment of cert-manager & node-feature-discovery

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#159]
Our deployment of Atmosphere includes a slightly different architecture for Kubernetes, including a custom deployment of cert-manager and node-feature-discovery. Like with ingress-nginx, please add a flag to the Atmosphere Operator that makes these optional deployments.

With node-feature-discovery, the current version of Atmosphere just results in a failed deployment and something that causes Atmosphere-Operator to crash. With cert-manager, it is actually successfully deploying cert-manager and unfortunately overriding our configuration, which is managed through other processes.

**Comment by thywyn** [comment]
It seems like the rabbitmq operator and the ApplyCertificateTask require atmosphere's helm release of cert-manager instead of requiring a designated valid clusterissuer in the cluster.  Putting in a config values of "clusterissuername" or something, then making cert-manager enabled would resolve this.. Working through a PR for this..

**Comment by mnaser** [comment]
Since we're moving out of the operator back to simple roles, this should be possible once we transition the cert-manager and nfd roles.

**Comment by mnaser** [comment]
this is now possible since they are separate role that you cant simply avoid running.
