### ISSUE TITLE
openvswitch error

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#173]
I try out the new atmosphere but on the openvswitch I use the following image: [cgm-quay.docker.artifactory.cgm.ag/vexxhost/openvswitch:2.17.0](http://cgm-quay.docker.artifactory.cgm.ag/vexxhost/openvswitch:2.17.0) But I get the following error:

root@ctl1:~# kubectl -n openstack logs pod/openvswitch-gcbj9 openvswitch-db-perms
chown: cannot access ‘/run/openvswitch’: No such file or directory

**Comment by mnaser** [comment]
updating this as critical as it seems to affect more than one user

**Comment by mnaser** [comment]
@mpiscaer can you checkout https://github.com/vexxhost/atmosphere/pull/175 ?

**Comment by thywyn** [comment]
Also looks like neutron-ovs-agent doesn't come up on a new builld because the new combined pods don't have the label of 'component: openvswitch-vswitchd' only the label 'component=server'.
`$ kubectl logs -n openstack neutron-ovs-agent-default-xhwgz -c init
...
Entrypoint WARNING: 2022/11/15 19:44:24 entrypoint.go:72: Resolving dependency Pod on same host with labels map[application:openvswitch component:openvswitch-vswitchd-db] in namespace openstack failed: Found no pods matching labels: map[application:openvswitch component:openvswitch-vswitchd-db] .
...`

**Comment by mpiscaer** [comment]
@thywyn Did you also checked #175 that solved that issue.

For now I only have the following issue left:

kubectl -n openstack describe pod/keepalived-8mw9c
....
Failed to pull image "cgm-quay.docker.artifactory.cgm.ag/vexxhost/keepalived:2.0.19": rpc error: code = NotFound desc = failed to pull and unpack image "cgm-quay.docker.artifactory.cgm.ag/vexxhost/keepalived:2.0.19": failed to resolve reference "cgm-quay.docker.artifactory.cgm.ag/vexxhost/keepalived:2.0.19": cgm-quay.docker.artifactory.cgm.ag/vexxhost/keepalived:2.0.19: not found

Probably this is something local

**Comment by thywyn** [comment]
Yep, just did it does not crash loop anymore, but the neuron-ovs-agent pod is still expecting the "component:openvswitch-vswitchd-db" label and the daemonset for openvswitch is assigning "component:server"

**Comment by thywyn** [comment]
Here's the culprit in openvswitch: https://github.com/vexxhost/openstack-helm-infra/blob/24726dffd6f1e5ac91620e92e04a782cb94340e8/openvswitch/templates/daemonset.yaml#L76

here's where openstack-helm/neutron is looking for the 2 labels:
https://opendev.org/openstack/openstack-helm/src/commit/3bc81054b0918678c5932663ea72821621280d5c/neutron/values.yaml#L285  
I think it would complain about no openvswitch-vswitchd after it resolved the openvswitch-vswitchd-db

**Comment by thywyn** [comment]
Ah, I see you've changed the repo to the vexxhost one.. don't know why my deploy didn't use that.. I'll look into that
