### ISSUE TITLE
pxc_strict_mode 

### ISSUE THREAD

**Issue by satrik** [vexxhost/atmosphere#1838]
hey there, 
is there a special reason why the pxc_strict_mode is set to ENFORCING instead of PERMISSIVE? 
I have problems if I try to delete loadbalancer flavors because of this.

```
root@ctr1:~# openstack loadbalancer flavor delete f678de63-705a-4b5b-8a83-8a56512085dd
(1105, "Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING") (HTTP 500) (Request-ID: req-b70d5ab8-348f-420d-b200-b1f16ee8e4e3)
```

if I just set the pxc_strict_mode variable to PERMISSIVE it works like expected

**Comment by okozachenko1203** [comment]
@satrik the fix landed to allow lb flavor deletion.
Btw, your original question was why ENFORCING in pxc. Here is the answer.
https://docs.percona.com/percona-xtradb-cluster/8.0/strict-mode.html

ENFORCING is the default mode because of its purpose as you can see in the doc
![image](https://github.com/user-attachments/assets/de85f52b-4d36-4220-a7e7-ca0ac536bb0b)

`openstack loadbalancer flavor delete` operation uses SERIALIZABLE isolation and it requires explicit table locking. We changed to MASTER which allows explicit table lock and it doesn't affect to our full system logic because technically we just write to one master node.
