### ISSUE TITLE
Update qemu and libvirt to properly support AMD Epyc Genoa CPUs  (zen4)

### ISSUE THREAD

**Issue by thywyn** [vexxhost/atmosphere#1933]
The versions of libvirt and qemu do not seem to identify our newer CPUs appropriately.  We don't know if this is affecting anything else.  They are coming back as "milan" not "genoa".  Support in qemu and libvirt seem to be with these versions:

https://github.com/qemu/qemu/commit/166b1741884dd4fd7090b753cd7333868457a29b            ##qemu 9.1.0+
https://gitlab.com/libvirt/libvirt/-/tree/v9.8.0/src/cpu_map?ref_type=tags

**Comment by mnaser** [comment]
The versions of QEMU and libvirt included in the current Atmosphere OpenStack deployment do not yet support the identification of AMD EPYC Genoa processors, causing them to be recognized as Milan. This is because the support for Genoa CPUs was introduced in newer versions of QEMU (9.1.0+) and libvirt (v9.8.0), which are not yet shipped in the Ubuntu repositories we use.

The main impact of this discrepancy is that some advanced features of the Genoa CPUs, such as various AVX-512 instruction sets (avx512f, avx512dq, etc.), la57 (57-bit virtual address support), and auto-ibrs (Automatic IBRS for security), will not be exposed to the VMs. While this could result in a slight performance reduction for certain workloads that depend on these features, such cases are rare and mostly limited to highly compute-intensive applications.

Since we do not currently plan to maintain our own builds of QEMU or libvirt, the CPUs will continue to be identified as Milan for the time being. This should not cause any major issues unless your workloads require those specific Genoa CPU features.

**Comment by thywyn** [comment]
any plans to use 24.04 server eventually?
