### ISSUE TITLE
Add log rotation for Loki

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#525]
We need to setup a log rotation in place to setup a tail like 365d logging or so.

**Comment by ricolin** [comment]
One solution I found is to set kubelet configs `containerLogMaxSize` and `containerLogMaxFiles` which also recommanded in loki document https://grafana.com/docs/loki/latest/clients/promtail/logrotation/#kubernetes
But that's gonna limit rotation by size instead of duration.
Is that a acceptable approach here?

Also didn't find anything log rotate parameter or method in grafana-agent-operator, so I think this might be the only straightforward solution here.

log working hours: 4

**Comment by yaguangtang** [comment]
I think we can enable loki compactor for indexing rotation, https://grafana.com/docs/loki/latest/operations/storage/retention/
